### ISSUE TITLE
Assignment 3, question 2

### ISSUE THREAD

**Issue by QinJi23** [BME1478H/Fall2022class#395]
In question 2 part c) of assignment 3, inside the for loop there is a variable called error. Would you mind clarifying what this error is supposed to be? Is it just the residuals (i.e., the difference between the simulated data (population_size_noise w/ varying rates) and the experimental data (population_size)? It is unclear what this variable is suppose to equate.

**Comment by RayNele** [comment]
You can just ignore that. Must be a typo from when we updated the assignment. 

```
 mse = [] # initialize a list to store our results
 for _____ in _____:
     prediction = _____
     mse._____(_____)
```
