### ISSUE TITLE
Assignment Submission

### ISSUE THREAD

**Issue by jlex13** [BME1478H/Fall2022class#396]
Hi, 
Apologies if this is clarified somewhere in Quercus but I could not find it.
What file type should we submit Assignment 3 as? PDF, .py or .ipynb?
Thank you

**Comment by mmaryam2020** [comment]
Submit the .ipynb file and make sure that you have run it once, and the output is shown in the notebook for each part.

**Comment by DavidCromp** [comment]
If we are not using Jupyter [Notebook] is it sufficient to submit a pdf with the output and the related code segment?

**Comment by RayNele** [comment]
@DavidCromp 

that makes it a little harder to mark, is there a specific reason you're not using jupyter notebook? I personally would rather have your .ipynb, .py and finally only as a last resort, a pdf.

**Comment by DavidCromp** [comment]
I had not used Jupyter Notebook as I already have a development environment that I was familiar with, it is simple enough to transpose the assignment to it, as I have done, and shall do for future assignments.

The rationale for thinking PDF was such that then it, like the ipynb would also include the program output. (My original submission contained a PDF with the code & output and the associated `.py` file)
