### ISSUE TITLE
A3Q2 clarification

### ISSUE THREAD

**Issue by AliBarzing** [BME1478H/Fall2022class#397]
Hello,

To my understanding, for Question 2 of Assignment#3 we should iterate over a range of parameter values, `range_rate`, and the population we are comparing our prediction with is the noisy population, right?

The residual should be something like below?

`residual = predicted - noisy`

The confusion is, I am not sure if we are comparing the predicted with the main `population_size` clean data or `population_size_noise` noisy data?

Could you also clarify: when we are generating the predicted population with different estimated rates from `range_rate` list, should we also add a normally distributed random noise to it, like what we did for noisy population, or not?

Should it be like (a) or (b)?

(a) `prediction = N0 * np.exp(some_rate_from_the_range_rate_list * t)`
or
(b) `prediction = N0 * np.exp(some_rate_from_the_range_rate_list * t) + normal_noise # Noise with mean=0 and std=250`

**Comment by DavidCromp** [comment]
When generating predicted data we are, as I interpret it, to calculate the residual with respect to `population_size_noise`.

> Let's assume we don't know the rate of the population growth, but we do have the data of the population size across time. Using the data you simulated 
in **_population_size_noise_**, estimate the rate by iterating over a range of parameter values and choosing the one with the best fit to the data.

With regards to adding noise to the prediction or not, based on how the instructions are phrased I believe we are supposed to generate the predicted data like (a):
> `prediction = N0 * np.exp(some_rate_from_the_range_rate_list * t)`
