### ISSUE TITLE
A8 Submission

### ISSUE THREAD

**Issue by pauloleong** [BME1478H/Fall2022class#522]
Dear TAs,

I submitted my assignment 8 just now and it showed that its late? I thought it's due before 11:59pm? no?

Best Regards,
Lok Leong

**Comment by RayNele** [comment]
Hi, for questions regarding visibility of marks, late submisisons, or general quercus issues, you can send your marking TA an email which we will then either try to fix on quercus, or forward to Prof Garton if the issue can't be fixed. 

Given that I do mark your assignments, I checked quercus and it doesn't show as late on my end, so I wouldn't worry about it :)
