### ISSUE TITLE
A102C: issue with fitted scatter plot

### ISSUE THREAD

**Issue by Chip123** [BME1478H/Fall2022class#525]
My code attached below is producing a really strange plot and I cannot figure out why. Thank you in advance for your help.

```ruby
formula_2 = 'co2_per_capita ~ income'
res2 = smf.ols(formula_2, data=world_data_2014).fit()
print(res2.summary())
sns.scatterplot(x ='income',y = 'co2_per_capita', data=world_data_2014)
plt.plot(world_data_2014.income,results.fittedvalues)
```

<img width="1222" alt="Screen Shot 2022-03-28 at 5 10 52 PM" src="https://user-images.githubusercontent.com/97861484/160487785-fd1c5f62-cad3-4385-8fc6-bb355fd35632.png">

**Comment by QinJi23** [comment]
your "results.fittedvalues" is from a previous fit, use "res2.fittedvalues"
